export {
  initXMTPClient,
  getClient,
  getInboxId,
  getOrCreateDM,
  listDMs,
  sendMessage,
  loadMessages,
  streamMessages,
  updateConsentState,
  disconnect,
  isConnected,
  ConsentState,
  type Dm,
  type DecodedMessage,
  type ListMessagesOptions,
} from './client'
